name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # -----------------------------
  # BUILD JOB (runs on GitHub cloud)
  # -----------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jamesjone
          password: ${{ secrets.JAMESJONE }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jamesjone/devops:latest

  # -----------------------------
  # DEPLOY JOB (runs on YOUR SELF-HOSTED MACHINE)
  # -----------------------------
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull latest image
        run: |
          docker pull jamesjone/devops:latest

      - name: Stop old container
        run: |
          docker stop devops || true
          docker rm devops || true

      - name: Run new container
        run: |
          docker run -d \
            --name devops \
            -p 80:3000 \
            jamesjone/devops:latest
